### Create new connection:
POST localhost:8080/connections
Content-Type: application/json

{
  "connectionName": "ClickHouse#1",
  "description": "get data from clickhouse",
  "host": "localhost",
  "port": 8123,
  "database": "test",
  "userName": "default",
  "password": "",
  "connectionProperties": []
}


### Show all connections with pagination
GET localhost:8080/connections?page=0&size=10

### Add new data model
POST localhost:8080/models
Content-Type: application/json

{
  "name": "ontime",
  "description": "Flight data",
  "connectionId": 1,
  "tableName": "ontime",
  "criteria": {
    "eq": {
       "fieldName": "Origin",
       "value": "JFK"
    }
  }
}

### Show all data models with pagination
GET localhost:8080/models?page=0&size=10

### Get data model by id
GET localhost:8080/models/1

### Create report:
POST localhost:8080/reports
Content-Type: application/json

{
  "name": "report1",
  "description": "The number of flights per day",
  "modelId": 1,
  "outputs": [
    "DayOfWeek",
    "count(*)"
  ],
  "groupBy": "DayOfWeek",
  "criteria": {
    "and": [
      {
        "ge": {
          "fieldName": "Year",
          "value": "1988"
        }
      },
      {
        "le": {
          "fieldName": "Year",
          "value": "1990"
        }
      }
    ]
  }
}


### Show all reports:
GET /reports?page=0&size=10