spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.engine.internal: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    io.github.eaxdev: DEBUG